### ISSUE TITLE
Toogle side nav does not appear when responsive mode

### ISSUE THREAD

**Issue by hervyqa** [statichunt/geeky-hugo#12]
Version: `hugo v0.94.2+extended linux/amd64 BuildDate=unknown`
OS: `voidlinux`

Step reproduce:
1. build in local.
```
hugo new site myweb
cd myweb
git clone --depth 1 git@github.com:gethugothemes/geeky-hugo.git themes/geeky-hugo
cp -rdv themes/geeky-hugo/exampleSite/* .
hugo server
```
2. open in browser `http://localhost:1313/geeky-hugo` (firefox desktop)
3. ctrl+shift+m (responsive mode)
4. click three bar icon, side nav does not appear.

Cast:

https://user-images.githubusercontent.com/45872139/158801542-3ec093fb-b81b-42ad-9c05-2c8bc375a96e.mp4

**Comment by gaetawoo** [comment]
Version: `hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb+extended windows/amd64 BuildDate=2022-03-26T09:15:58Z`
OS: Windows 10

The reason this happens is because the javascript is being minified and the object variables are being jumbled so the function to open the menu can run.

See Issue #13 
The fix is referenced in the issue... in the `/themes/geeky-hugo/layouts/partials/script.html` in Line 11, remove the minify command and rebuild the site. It should work after that.

**Comment by tfsomrat** [comment]
Hello @hervyqa 

Sorry for the late response, this issue has been fixed now. you can check it after downloading the latest code, thank you.

**Comment by hervyqa** [comment]
Ok. Thank you @tfsomrat
